version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 20
      runas: ec2-user
