name: Build Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Clone Github Repo
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM Dependencies & Create Frontend Build
      working-directory: ./frontend/court-up
      run: |
        npm install
        npm run build
        
    - name: Copy Frontend Build To Backend Static Files
      run: |
        cd backend/CourtUpAPI/src/main/resources/
        mkdir static
        cd ../../../../../
        cp -R ./frontend/court-up/build/* ./backend/CourtUpAPI/src/main/resources/static/
        
    - name: Inject Environment Variables
      working-directory: ./backend/CourtUpAPI/src/main/resources/
      run: |
        rm application.properties
        touch application.properties
        
        echo "${{ secrets.COURTUP_APPLICATION_PROPERTIES }}" > application.properties
        cat application.properties
        
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build Backend with Maven
      working-directory: ./backend/CourtUpAPI/
      run: mvn -B package --file pom.xml
      
    - name: Upload Artifact To Github
      uses: actions/upload-artifact@v2
      with: 
        name: courtup-build
        path: ./backend/CourtUpAPI/target/
        
