name: Build Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Clone Github Repo
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM Dependencies & Create Frontend Build
      working-directory: ./frontend/court-up
      run: |
        npm install
        npm run build
        
    - name: Copy Frontend Build To Backend Static Files
      run: |
        cd backend/CourtUpAPI/src/main/resources/
        mkdir static
        cd ../../../../../
        cp -R ./frontend/court-up/build/* ./backend/CourtUpAPI/src/main/resources/static/
        
    - name: Inject Environment Variables
      working-directory: ./backend/CourtUpAPI/src/main/resources/
      run: |
        rm application.properties
        touch application.properties
        
        echo spring.datasource.url=${{ secrets.COURTUP_DB_CONNECTION }} >> .application.properties
        echo spring.datasource.username=${{ secrets.COURTUP_DB_USERNAME }} >> .application.properties
        echo spring.datasource.password=${{ secrets.COURTUP_DB_PASSWORD }} >> .application.properties
        echo spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver >> .application.properties

        echo spring.jpa.hibernate.ddl-auto=update >> .application.properties
        echo spring.jpa.properties.hibernate.show_sql=true >> .application.properties

        echo server.port=${PORT:8080} >> .application.properties
        echo server.servlet.context-path=/ >> .application.properties
        echo logging.file.name=application.log >> .application.properties
        echo logging.level.org.springFramework=DEBUG >> .application.properties
        
        cat application.properties
        
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build Backend with Maven
      working-directory: ./backend/CourtUpAPI/
      run: mvn -B package --file pom.xml
      
    - name: Upload Artifact To Github
      uses: actions/upload-artifact@v2
      with: 
        name: courtup-build
        path: ./backend/CourtUpAPI/target/
        
